// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package expert

import (
	"fmt"
	"io"

	abi "github.com/filecoin-project/go-state-types/abi"
	builtin "github.com/filecoin-project/specs-actors/v2/actors/builtin"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf

var lengthBufState = []byte{136}

func (t *State) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufState); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Info (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.Info); err != nil {
		return xerrors.Errorf("failed to write cid field t.Info: %w", err)
	}

	// t.Datas (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.Datas); err != nil {
		return xerrors.Errorf("failed to write cid field t.Datas: %w", err)
	}

	// t.DataCount (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.DataCount)); err != nil {
		return err
	}

	// t.ExpertState (expert.ExpertState) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.ExpertState)); err != nil {
		return err
	}

	// t.ImplicatedTimes (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.ImplicatedTimes)); err != nil {
		return err
	}

	// t.CurrentVotes (big.Int) (struct)
	if err := t.CurrentVotes.MarshalCBOR(w); err != nil {
		return err
	}

	// t.EpochDate (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.EpochDate)); err != nil {
		return err
	}

	// t.DailyImportSize (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.DailyImportSize)); err != nil {
		return err
	}

	return nil
}

func (t *State) UnmarshalCBOR(r io.Reader) error {
	*t = State{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 8 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Info (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.Info: %w", err)
		}

		t.Info = c

	}
	// t.Datas (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.Datas: %w", err)
		}

		t.Datas = c

	}
	// t.DataCount (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.DataCount = uint64(extra)

	}
	// t.ExpertState (expert.ExpertState) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.ExpertState = ExpertState(extra)

	}
	// t.ImplicatedTimes (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.ImplicatedTimes = uint64(extra)

	}
	// t.CurrentVotes (big.Int) (struct)

	{

		if err := t.CurrentVotes.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.CurrentVotes: %w", err)
		}

	}
	// t.EpochDate (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.EpochDate = uint64(extra)

	}
	// t.DailyImportSize (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.DailyImportSize = uint64(extra)

	}
	return nil
}

var lengthBufExpertInfo = []byte{134}

func (t *ExpertInfo) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufExpertInfo); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Owner (address.Address) (struct)
	if err := t.Owner.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Type (builtin.ExpertType) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Type)); err != nil {
		return err
	}

	// t.ApplicationHash (string) (string)
	if len(t.ApplicationHash) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.ApplicationHash was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.ApplicationHash))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.ApplicationHash)); err != nil {
		return err
	}

	// t.Proposer (address.Address) (struct)
	if err := t.Proposer.MarshalCBOR(w); err != nil {
		return err
	}

	// t.ApplyNewOwner (address.Address) (struct)
	if err := t.ApplyNewOwner.MarshalCBOR(w); err != nil {
		return err
	}

	// t.ApplyNewOwnerEpoch (abi.ChainEpoch) (int64)
	if t.ApplyNewOwnerEpoch >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.ApplyNewOwnerEpoch)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.ApplyNewOwnerEpoch-1)); err != nil {
			return err
		}
	}
	return nil
}

func (t *ExpertInfo) UnmarshalCBOR(r io.Reader) error {
	*t = ExpertInfo{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Owner (address.Address) (struct)

	{

		if err := t.Owner.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Owner: %w", err)
		}

	}
	// t.Type (builtin.ExpertType) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Type = builtin.ExpertType(extra)

	}
	// t.ApplicationHash (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.ApplicationHash = string(sval)
	}
	// t.Proposer (address.Address) (struct)

	{

		if err := t.Proposer.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Proposer: %w", err)
		}

	}
	// t.ApplyNewOwner (address.Address) (struct)

	{

		if err := t.ApplyNewOwner.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.ApplyNewOwner: %w", err)
		}

	}
	// t.ApplyNewOwnerEpoch (abi.ChainEpoch) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.ApplyNewOwnerEpoch = abi.ChainEpoch(extraI)
	}
	return nil
}

var lengthBufDataOnChainInfo = []byte{132}

func (t *DataOnChainInfo) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufDataOnChainInfo); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.RootID (string) (string)
	if len(t.RootID) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.RootID was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.RootID))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.RootID)); err != nil {
		return err
	}

	// t.PieceID (string) (string)
	if len(t.PieceID) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.PieceID was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.PieceID))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.PieceID)); err != nil {
		return err
	}

	// t.PieceSize (abi.PaddedPieceSize) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.PieceSize)); err != nil {
		return err
	}

	// t.Redundancy (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Redundancy)); err != nil {
		return err
	}

	return nil
}

func (t *DataOnChainInfo) UnmarshalCBOR(r io.Reader) error {
	*t = DataOnChainInfo{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RootID (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.RootID = string(sval)
	}
	// t.PieceID (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.PieceID = string(sval)
	}
	// t.PieceSize (abi.PaddedPieceSize) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.PieceSize = abi.PaddedPieceSize(extra)

	}
	// t.Redundancy (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Redundancy = uint64(extra)

	}
	return nil
}

var lengthBufConstructorParams = []byte{132}

func (t *ConstructorParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufConstructorParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Owner (address.Address) (struct)
	if err := t.Owner.MarshalCBOR(w); err != nil {
		return err
	}

	// t.ApplicationHash (string) (string)
	if len(t.ApplicationHash) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.ApplicationHash was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.ApplicationHash))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.ApplicationHash)); err != nil {
		return err
	}

	// t.Proposer (address.Address) (struct)
	if err := t.Proposer.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Type (builtin.ExpertType) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Type)); err != nil {
		return err
	}

	return nil
}

func (t *ConstructorParams) UnmarshalCBOR(r io.Reader) error {
	*t = ConstructorParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Owner (address.Address) (struct)

	{

		if err := t.Owner.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Owner: %w", err)
		}

	}
	// t.ApplicationHash (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.ApplicationHash = string(sval)
	}
	// t.Proposer (address.Address) (struct)

	{

		if err := t.Proposer.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Proposer: %w", err)
		}

	}
	// t.Type (builtin.ExpertType) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Type = builtin.ExpertType(extra)

	}
	return nil
}

var lengthBufBatchImportDataParams = []byte{129}

func (t *BatchImportDataParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufBatchImportDataParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Datas ([]expert.ImportDataParams) (slice)
	if len(t.Datas) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.Datas was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Datas))); err != nil {
		return err
	}
	for _, v := range t.Datas {
		if err := v.MarshalCBOR(w); err != nil {
			return err
		}
	}
	return nil
}

func (t *BatchImportDataParams) UnmarshalCBOR(r io.Reader) error {
	*t = BatchImportDataParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Datas ([]expert.ImportDataParams) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.Datas: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Datas = make([]ImportDataParams, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v ImportDataParams
		if err := v.UnmarshalCBOR(br); err != nil {
			return err
		}

		t.Datas[i] = v
	}

	return nil
}

var lengthBufChangeInfoParams = []byte{129}

func (t *ChangeInfoParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufChangeInfoParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.ApplicationHash (string) (string)
	if len(t.ApplicationHash) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.ApplicationHash was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.ApplicationHash))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.ApplicationHash)); err != nil {
		return err
	}
	return nil
}

func (t *ChangeInfoParams) UnmarshalCBOR(r io.Reader) error {
	*t = ChangeInfoParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.ApplicationHash (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.ApplicationHash = string(sval)
	}
	return nil
}

var lengthBufImportDataParams = []byte{131}

func (t *ImportDataParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufImportDataParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.RootID (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.RootID); err != nil {
		return xerrors.Errorf("failed to write cid field t.RootID: %w", err)
	}

	// t.PieceID (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.PieceID); err != nil {
		return xerrors.Errorf("failed to write cid field t.PieceID: %w", err)
	}

	// t.PieceSize (abi.PaddedPieceSize) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.PieceSize)); err != nil {
		return err
	}

	return nil
}

func (t *ImportDataParams) UnmarshalCBOR(r io.Reader) error {
	*t = ImportDataParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.RootID (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.RootID: %w", err)
		}

		t.RootID = c

	}
	// t.PieceID (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.PieceID: %w", err)
		}

		t.PieceID = c

	}
	// t.PieceSize (abi.PaddedPieceSize) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.PieceSize = abi.PaddedPieceSize(extra)

	}
	return nil
}

var lengthBufGetDatasReturn = []byte{130}

func (t *GetDatasReturn) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufGetDatasReturn); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Infos ([]*expert.DataOnChainInfo) (slice)
	if len(t.Infos) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.Infos was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Infos))); err != nil {
		return err
	}
	for _, v := range t.Infos {
		if err := v.MarshalCBOR(w); err != nil {
			return err
		}
	}

	// t.ExpertBlocked (bool) (bool)
	if err := cbg.WriteBool(w, t.ExpertBlocked); err != nil {
		return err
	}
	return nil
}

func (t *GetDatasReturn) UnmarshalCBOR(r io.Reader) error {
	*t = GetDatasReturn{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Infos ([]*expert.DataOnChainInfo) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.Infos: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Infos = make([]*DataOnChainInfo, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v DataOnChainInfo
		if err := v.UnmarshalCBOR(br); err != nil {
			return err
		}

		t.Infos[i] = &v
	}

	// t.ExpertBlocked (bool) (bool)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.ExpertBlocked = false
	case 21:
		t.ExpertBlocked = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufOnBlockedReturn = []byte{130}

func (t *OnBlockedReturn) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufOnBlockedReturn); err != nil {
		return err
	}

	// t.ImplicatedExpert (address.Address) (struct)
	if err := t.ImplicatedExpert.MarshalCBOR(w); err != nil {
		return err
	}

	// t.ImplicatedExpertVotesEnough (bool) (bool)
	if err := cbg.WriteBool(w, t.ImplicatedExpertVotesEnough); err != nil {
		return err
	}
	return nil
}

func (t *OnBlockedReturn) UnmarshalCBOR(r io.Reader) error {
	*t = OnBlockedReturn{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.ImplicatedExpert (address.Address) (struct)

	{

		if err := t.ImplicatedExpert.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.ImplicatedExpert: %w", err)
		}

	}
	// t.ImplicatedExpertVotesEnough (bool) (bool)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.ImplicatedExpertVotesEnough = false
	case 21:
		t.ImplicatedExpertVotesEnough = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufOnVotesUpdatedReturn = []byte{129}

func (t *OnVotesUpdatedReturn) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufOnVotesUpdatedReturn); err != nil {
		return err
	}

	// t.VotesEnough (bool) (bool)
	if err := cbg.WriteBool(w, t.VotesEnough); err != nil {
		return err
	}
	return nil
}

func (t *OnVotesUpdatedReturn) UnmarshalCBOR(r io.Reader) error {
	*t = OnVotesUpdatedReturn{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.VotesEnough (bool) (bool)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.VotesEnough = false
	case 21:
		t.VotesEnough = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}
